


### Security Requests



###
GET /api/v1/security/csrf-token
Host: localhost:9000
Accept: application/json



### IdentityRequests



###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 60c15b3c-00e1-4ff8-b9c5-336520ad5c71

{
    "authority": "USER",
    "username": "zagor",
    "password": "zagor",
    "email": "zagor@gmail.com",
    "firstname": "Загорулько",
    "lastname": "Борис",
    "patronymic": "Юрьевич"
}

###
PUT /api/v1/identities/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: dcd25966-4dda-4b51-9c08-a5cd7c53204f
Authorization: Basic zagor@gmail.com zagor

{
    "id": "3150c6af-9286-4378-a8e7-c43937a09327",
    "username": "zagorulko"
}

###
GET /api/v1/identities
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/identities/by-id?identityId=c009193f-54bc-4360-924c-893c2856f201
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
DELETE /api/v1/identities/delete?identityId=d530dcd2-6931-47fa-a895-ce2cee102820
Host: localhost:9000
Accept: application/json



### Car Requests



###
GET /api/v1/cars
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/cars/by-identity?identityId=c009193f-54bc-4360-924c-893c2856f201
Host: localhost:9000
Accept: application/json
Authorization: Basic zagor@gmail.com zagor

###
GET /api/v1/cars/by-id?carId=a16206b2-d498-4878-92d5-607495becf91
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/cars/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: a889a7bd-0c0d-4c9c-a1d4-7180e9757495
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "brand": "Porsche",
    "model": "911",
    "description": "Описание и характеристики автомобиля Porsche 911",
    "identityId": "c009193f-54bc-4360-924c-893c2856f201"
}

###
PUT /api/v1/cars/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: b6dad7e3-9f50-4362-b888-aa9841e3def0
Authorization: Basic zagor@gmail.com zagor

{
    "id": "1251a88f-3f0c-492f-b57c-c1402bb9f553",
    "model": "911-Turbo",
    "description": "Описание и характеристики автомобиля 911-Turbo"
}



### Address Requests



###
GET /api/v1/addresses
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/addresses/by-id?addressId=50cbc8c9-f8c5-45fe-8e46-c36406a16066
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/addresses/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: d2bcd8f7-42f5-4fe7-af06-631f16e71fbf
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "city": "Москва",
    "street": "Мясницкая",
    "house": "12/1"
}

###
PUT /api/v1/addresses/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: d2bcd8f7-42f5-4fe7-af06-631f16e71fbf
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "34c8fb13-d5c6-4aed-a833-05e7d5aaa77c",
    "house": "34/2"
}



### Parking Requests



###
GET /api/v1/parking
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/parking/by-id?parkingId=727a39a2-3ce0-4d4c-b489-bc8a9c1a2827
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/parking/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 740c75dd-b643-4b9f-8bd4-717365a0af7a
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "address": {
        "city": "Омск",
        "street": "Маяковского",
        "house": "25"
    },
    "price": 1200.50
}

###
POST /api/v1/parking/add-cars
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: d2bcd8f7-42f5-4fe7-af06-631f16e71fbf
Authorization: Basic burgasvv@gmail.com burgasvv

[
    {
        "parkingId": "17be8c12-3dae-4334-b25c-ca37d1cd70f3",
        "carId": "1251a88f-3f0c-492f-b57c-c1402bb9f553"
    }
]